2017-04-20 14:10:16.335 [error] <0.3378.0> CRASH REPORT Process <0.3378.0> with 1 neighbours exited with reason: {connection_error,{connection_error,econnrefused}} in gen_server:init_it/6 line 344
2017-04-20 14:10:16.335 [error] <0.3306.0> Supervisor lasp_sup had child lasp_workflow started with lasp_workflow:start_link() at undefined exit with reason {connection_error,{connection_error,econnrefused}} in context start_error
2017-04-20 14:10:16.337 [error] <0.3304.0> CRASH REPORT Process <0.3304.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,lasp_workflow,{connection_error,{connection_error,econnrefused}}}},{lasp_app,start,[normal,[]]}} in application_master:init/4 line 134
